// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cavgjeederarxrawaxfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdmdqZWVkZXJhcnhyYXdheGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzcwOTQsImV4cCI6MjA2MDMxMzA5NH0.3mDTIWEGupzwWH5emkpcX4emmITQ-zcdUMClwID1944";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);